name: Build iOS Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # レポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 必要なパッケージをインストール
    - name: Install dependencies
      run: |
        brew update
        brew install libimobiledevice libimobiledevice-glue autoconf automake

    # Homebrewのパスを取得
    - name: Get Homebrew prefix
      run: echo "HOMEBREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV

    # iOS向けにコンパイル
    - name: Build for iOS arm64
      run: |
        mkdir -p build/iphoneos
        clang main.c \
          -o build/iphoneos/main \
          -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -fembed-bitcode \
          -mios-version-min=10.0 \
          -I$GITHUB_WORKSPACE/common \
          -I$HOMEBREW_PREFIX/include \
          -I$HOMEBREW_PREFIX/include/libimobiledevice-glue \
          -L$HOMEBREW_PREFIX/lib \
          -limobiledevice

    # コンパイル結果をアーティファクトとしてアップロード
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iOS-binary
        path: build/iphoneos/main
