name: Build iOS Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install libimobiledevice libimobiledevice-glue

    - name: Verify installed libraries
      run: |
        ls /usr/local/include
        ls /usr/local/lib

    - name: Build for iOS arm64
      run: |
        mkdir -p build/iphoneos
        clang main.c \
          -o build/iphoneos/main \
          -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -fembed-bitcode \
          -mios-version-min=10.0 \
          -I/usr/local/include \
          -I/usr/local/include/libimobiledevice-glue \
          -L/usr/local/lib \
          -limobiledevice

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iOS-binary
        path: build/iphoneos/main
